///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TempusSimulatorDemoTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Events element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b4a76f51-171f-44d2-90b3-db61ed64877b")]
    public partial class Events : RepoGenBaseFolder
    {
        static Events instance = new Events();
        EventsFolders.Report_TypeFolder _report_type;
        EventsFolders.InterventionFolder _intervention;
        EventsFolders.FluidFolder _fluid;
        EventsFolders.DrugFolder _drug;
        EventsFolders.GeneralFolder _general;
        EventsFolders.InjuryFolder _injury;
        EventsFolders.DressingFolder _dressing;
        EventsFolders.BurnFolder _burn;
        EventsFolders.TempusProConfigurationUtilityAppFolder _tempusproconfigurationutility;
        EventsFolders.EventEditorAppFolder _eventeditor;
        EventsFolders.AddEventAppFolder _addevent;
        EventsFolders.EditEventAppFolder _editevent;

        /// <summary>
        /// Gets the singleton class instance representing the Events element repository.
        /// </summary>
        [RepositoryFolder("b4a76f51-171f-44d2-90b3-db61ed64877b")]
        public static Events Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Events() 
            : base("Events", "/", null, 0, false, "b4a76f51-171f-44d2-90b3-db61ed64877b", ".\\RepositoryImages\\Eventsb4a76f51.rximgres")
        {
            _report_type = new EventsFolders.Report_TypeFolder(this);
            _intervention = new EventsFolders.InterventionFolder(this);
            _fluid = new EventsFolders.FluidFolder(this);
            _drug = new EventsFolders.DrugFolder(this);
            _general = new EventsFolders.GeneralFolder(this);
            _injury = new EventsFolders.InjuryFolder(this);
            _dressing = new EventsFolders.DressingFolder(this);
            _burn = new EventsFolders.BurnFolder(this);
            _tempusproconfigurationutility = new EventsFolders.TempusProConfigurationUtilityAppFolder(this);
            _eventeditor = new EventsFolders.EventEditorAppFolder(this);
            _addevent = new EventsFolders.AddEventAppFolder(this);
            _editevent = new EventsFolders.EditEventAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b4a76f51-171f-44d2-90b3-db61ed64877b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Report_Type folder.
        /// </summary>
        [RepositoryFolder("bb3cb258-9325-4555-9919-e53f4a90f88b")]
        public virtual EventsFolders.Report_TypeFolder Report_Type
        {
            get { return _report_type; }
        }

        /// <summary>
        /// The Intervention folder.
        /// </summary>
        [RepositoryFolder("125dded6-3fcd-41f6-b0d7-335bca7b8183")]
        public virtual EventsFolders.InterventionFolder Intervention
        {
            get { return _intervention; }
        }

        /// <summary>
        /// The Fluid folder.
        /// </summary>
        [RepositoryFolder("a960e3da-1506-4694-88f0-f5e056ca8a6b")]
        public virtual EventsFolders.FluidFolder Fluid
        {
            get { return _fluid; }
        }

        /// <summary>
        /// The Drug folder.
        /// </summary>
        [RepositoryFolder("25b8f0d0-ecd9-4b49-b837-87e2592a41dd")]
        public virtual EventsFolders.DrugFolder Drug
        {
            get { return _drug; }
        }

        /// <summary>
        /// The General folder.
        /// </summary>
        [RepositoryFolder("3ec0c71c-7ce5-489a-a4d4-b47e6a2a7170")]
        public virtual EventsFolders.GeneralFolder General
        {
            get { return _general; }
        }

        /// <summary>
        /// The Injury folder.
        /// </summary>
        [RepositoryFolder("40389da1-4ec4-4ac4-9bc4-0ace2eb72c8f")]
        public virtual EventsFolders.InjuryFolder Injury
        {
            get { return _injury; }
        }

        /// <summary>
        /// The Dressing folder.
        /// </summary>
        [RepositoryFolder("cb4b15b4-6a86-4232-b276-cd1dba051f65")]
        public virtual EventsFolders.DressingFolder Dressing
        {
            get { return _dressing; }
        }

        /// <summary>
        /// The Burn folder.
        /// </summary>
        [RepositoryFolder("2bc21cda-854e-48d3-ac3c-c71592c28994")]
        public virtual EventsFolders.BurnFolder Burn
        {
            get { return _burn; }
        }

        /// <summary>
        /// The TempusProConfigurationUtility folder.
        /// </summary>
        [RepositoryFolder("3abe4702-7a2a-49b5-9ce5-6bffc3b79c09")]
        public virtual EventsFolders.TempusProConfigurationUtilityAppFolder TempusProConfigurationUtility
        {
            get { return _tempusproconfigurationutility; }
        }

        /// <summary>
        /// The EventEditor folder.
        /// </summary>
        [RepositoryFolder("d366b60e-7983-4b93-86d7-dfa7102a6af6")]
        public virtual EventsFolders.EventEditorAppFolder EventEditor
        {
            get { return _eventeditor; }
        }

        /// <summary>
        /// The AddEvent folder.
        /// </summary>
        [RepositoryFolder("a486d313-ff3b-4730-9492-0d89acb5363b")]
        public virtual EventsFolders.AddEventAppFolder AddEvent
        {
            get { return _addevent; }
        }

        /// <summary>
        /// The EditEvent folder.
        /// </summary>
        [RepositoryFolder("7ac9a3bc-1bf2-428f-b9df-d7570de27621")]
        public virtual EventsFolders.EditEventAppFolder EditEvent
        {
            get { return _editevent; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EventsFolders
    {
        /// <summary>
        /// The Report_TypeFolder folder.
        /// </summary>
        [RepositoryFolder("bb3cb258-9325-4555-9919-e53f4a90f88b")]
        public partial class Report_TypeFolder : RepoGenBaseFolder
        {
            EventsFolders.TempusProConfigurationUtility1AppFolder _tempusproconfigurationutility1;

            /// <summary>
            /// Creates a new Report_Type  folder.
            /// </summary>
            public Report_TypeFolder(RepoGenBaseFolder parentFolder) :
                    base("Report_Type", "", parentFolder, 0, null, false, "bb3cb258-9325-4555-9919-e53f4a90f88b", "")
            {
                _tempusproconfigurationutility1 = new EventsFolders.TempusProConfigurationUtility1AppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb3cb258-9325-4555-9919-e53f4a90f88b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TempusProConfigurationUtility1 folder.
            /// </summary>
            [RepositoryFolder("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual EventsFolders.TempusProConfigurationUtility1AppFolder TempusProConfigurationUtility1
            {
                get { return _tempusproconfigurationutility1; }
            }
        }

        /// <summary>
        /// The TempusProConfigurationUtility1AppFolder folder.
        /// </summary>
        [RepositoryFolder("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
        public partial class TempusProConfigurationUtility1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tc3_reporttypeInfo;
            RepoItemInfo _highlighttc3linkedeventsInfo;

            /// <summary>
            /// Creates a new TempusProConfigurationUtility1  folder.
            /// </summary>
            public TempusProConfigurationUtility1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("TempusProConfigurationUtility1", "/contextmenu[@processname='Tempus Pro Configuration Utility']", parentFolder, 30000, null, false, "62c266cf-85b9-42ab-a1ab-a3eb362160fc", "")
            {
                _tc3_reporttypeInfo = new RepoItemInfo(this, "TC3_ReportType", "?/?/listitem[@text='TC3']", 30000, null, "26dc1e1c-fdc6-4918-9c3d-39254a2492e8");
                _highlighttc3linkedeventsInfo = new RepoItemInfo(this, "HighlightTC3LinkedEvents", "?/?/text[@caption>'Highlight TC3 linked even']", 30000, null, "24c34580-94e3-4725-9352-5a8e125bf30e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TC3_ReportType item.
            /// </summary>
            [RepositoryItem("26dc1e1c-fdc6-4918-9c3d-39254a2492e8")]
            public virtual Ranorex.ListItem TC3_ReportType
            {
                get
                {
                    return _tc3_reporttypeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TC3_ReportType item info.
            /// </summary>
            [RepositoryItemInfo("26dc1e1c-fdc6-4918-9c3d-39254a2492e8")]
            public virtual RepoItemInfo TC3_ReportTypeInfo
            {
                get
                {
                    return _tc3_reporttypeInfo;
                }
            }

            /// <summary>
            /// The HighlightTC3LinkedEvents item.
            /// </summary>
            [RepositoryItem("24c34580-94e3-4725-9352-5a8e125bf30e")]
            public virtual Ranorex.Text HighlightTC3LinkedEvents
            {
                get
                {
                    return _highlighttc3linkedeventsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The HighlightTC3LinkedEvents item info.
            /// </summary>
            [RepositoryItemInfo("24c34580-94e3-4725-9352-5a8e125bf30e")]
            public virtual RepoItemInfo HighlightTC3LinkedEventsInfo
            {
                get
                {
                    return _highlighttc3linkedeventsInfo;
                }
            }
        }

        /// <summary>
        /// The InterventionFolder folder.
        /// </summary>
        [RepositoryFolder("125dded6-3fcd-41f6-b0d7-335bca7b8183")]
        public partial class InterventionFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Intervention  folder.
            /// </summary>
            public InterventionFolder(RepoGenBaseFolder parentFolder) :
                    base("Intervention", "", parentFolder, 0, null, false, "125dded6-3fcd-41f6-b0d7-335bca7b8183", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("125dded6-3fcd-41f6-b0d7-335bca7b8183")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FluidFolder folder.
        /// </summary>
        [RepositoryFolder("a960e3da-1506-4694-88f0-f5e056ca8a6b")]
        public partial class FluidFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Fluid  folder.
            /// </summary>
            public FluidFolder(RepoGenBaseFolder parentFolder) :
                    base("Fluid", "", parentFolder, 0, null, false, "a960e3da-1506-4694-88f0-f5e056ca8a6b", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a960e3da-1506-4694-88f0-f5e056ca8a6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DrugFolder folder.
        /// </summary>
        [RepositoryFolder("25b8f0d0-ecd9-4b49-b837-87e2592a41dd")]
        public partial class DrugFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Drug  folder.
            /// </summary>
            public DrugFolder(RepoGenBaseFolder parentFolder) :
                    base("Drug", "", parentFolder, 0, null, false, "25b8f0d0-ecd9-4b49-b837-87e2592a41dd", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("25b8f0d0-ecd9-4b49-b837-87e2592a41dd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GeneralFolder folder.
        /// </summary>
        [RepositoryFolder("3ec0c71c-7ce5-489a-a4d4-b47e6a2a7170")]
        public partial class GeneralFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new General  folder.
            /// </summary>
            public GeneralFolder(RepoGenBaseFolder parentFolder) :
                    base("General", "", parentFolder, 0, null, false, "3ec0c71c-7ce5-489a-a4d4-b47e6a2a7170", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ec0c71c-7ce5-489a-a4d4-b47e6a2a7170")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The InjuryFolder folder.
        /// </summary>
        [RepositoryFolder("40389da1-4ec4-4ac4-9bc4-0ace2eb72c8f")]
        public partial class InjuryFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Injury  folder.
            /// </summary>
            public InjuryFolder(RepoGenBaseFolder parentFolder) :
                    base("Injury", "", parentFolder, 0, null, false, "40389da1-4ec4-4ac4-9bc4-0ace2eb72c8f", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40389da1-4ec4-4ac4-9bc4-0ace2eb72c8f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DressingFolder folder.
        /// </summary>
        [RepositoryFolder("cb4b15b4-6a86-4232-b276-cd1dba051f65")]
        public partial class DressingFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dressing  folder.
            /// </summary>
            public DressingFolder(RepoGenBaseFolder parentFolder) :
                    base("Dressing", "", parentFolder, 0, null, false, "cb4b15b4-6a86-4232-b276-cd1dba051f65", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb4b15b4-6a86-4232-b276-cd1dba051f65")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The BurnFolder folder.
        /// </summary>
        [RepositoryFolder("2bc21cda-854e-48d3-ac3c-c71592c28994")]
        public partial class BurnFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Burn  folder.
            /// </summary>
            public BurnFolder(RepoGenBaseFolder parentFolder) :
                    base("Burn", "", parentFolder, 0, null, false, "2bc21cda-854e-48d3-ac3c-c71592c28994", "")
            {
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2bc21cda-854e-48d3-ac3c-c71592c28994")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The TempusProConfigurationUtilityAppFolder folder.
        /// </summary>
        [RepositoryFolder("3abe4702-7a2a-49b5-9ce5-6bffc3b79c09")]
        public partial class TempusProConfigurationUtilityAppFolder : RepoGenBaseFolder
        {
            EventsFolders.MainDGFolder _maindg;
            RepoItemInfo _eventsInfo;
            RepoItemInfo _assessmentInfo;
            RepoItemInfo _groupend_bleedingInfo;
            RepoItemInfo _generalInfo;
            RepoItemInfo _addeventInfo;
            RepoItemInfo _yesbuttonformultiplefunctionsInfo;
            RepoItemInfo _addlabelInfo;
            RepoItemInfo _addblankInfo;
            RepoItemInfo _deletebuttonInfo;
            RepoItemInfo _editbuttonInfo;
            RepoItemInfo _fileInfo;
            RepoItemInfo _reporttypedropdownInfo;
            RepoItemInfo _settingsInfo;
            RepoItemInfo _clearallbuttonInfo;
            RepoItemInfo _downbuttonInfo;

            /// <summary>
            /// Creates a new TempusProConfigurationUtility  folder.
            /// </summary>
            public TempusProConfigurationUtilityAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TempusProConfigurationUtility", "/form[@title>'Tempus Pro Configuration']", parentFolder, 30000, null, true, "3abe4702-7a2a-49b5-9ce5-6bffc3b79c09", "")
            {
                _maindg = new EventsFolders.MainDGFolder(this);
                _eventsInfo = new RepoItemInfo(this, "Events", "?/?/tabpagelist[@automationid='mainTab']/?/?/text[@caption='Events']", 30000, null, "4183af41-4796-44a1-bd7e-2a12007c9685");
                _assessmentInfo = new RepoItemInfo(this, "Assessment", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnObservation']/?/?/text[@automationid='txtObservation']", 30000, null, "f467e039-f019-4623-a22f-fc7c774a4428");
                _groupend_bleedingInfo = new RepoItemInfo(this, "GroupEnd_Bleeding", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/table[@automationid='mainDG']/?/?/row[@index='0']/list/?/?/checkbox", 30000, null, "d96134e7-3d36-4879-a68b-fa7b2edf4f8a");
                _generalInfo = new RepoItemInfo(this, "General", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnGeneral']", 30000, null, "8cf123a8-22ae-4d60-aef2-87fe8cadd2b5");
                _addeventInfo = new RepoItemInfo(this, "AddEvent", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnAdd']/?/?/text[@automationid='txtAdd']", 30000, null, "939785a1-caff-4f77-84f7-8c1a91a5daa7");
                _yesbuttonformultiplefunctionsInfo = new RepoItemInfo(this, "YesButtonForMultipleFunctions", "button[@text='&Yes']", 30000, null, "ef085c54-f750-4259-9f5d-406068e77ac7");
                _addlabelInfo = new RepoItemInfo(this, "AddLabel", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnLabel']/?/?/text[@automationid='txtLabel']", 30000, null, "d7a16218-0d86-4e14-9a03-eef36d86bf7f");
                _addblankInfo = new RepoItemInfo(this, "AddBlank", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnBlankButton']/?/?/text[@automationid='txtBlankButton']", 30000, null, "9af0fb06-20ae-4605-94bb-21c649c61aae");
                _deletebuttonInfo = new RepoItemInfo(this, "DeleteButton", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnDelete']/?/?/text[@automationid='txtDelete']", 30000, null, "2ca62249-66d3-4bfa-b4fb-bc405ece68b5");
                _editbuttonInfo = new RepoItemInfo(this, "EditButton", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnEdit']/?/?/text[@automationid='txtEdit']", 30000, null, "df487ab5-509c-4e26-8661-415914efae77");
                _fileInfo = new RepoItemInfo(this, "File", "?/?/menuitem[@text='File']/text[@caption='File']", 30000, null, "727965fd-e55a-485c-865f-45460c41236a");
                _reporttypedropdownInfo = new RepoItemInfo(this, "ReportTypeDropDown", "?/?/tabpagelist[@automationid='mainTab']//combobox[@automationid='cmbReportType']/button[@automationid='toggleButton']", 30000, null, "2fe382a2-9685-4939-9d9f-f9bded694e2e");
                _settingsInfo = new RepoItemInfo(this, "Settings", "?/?/menuitem[@text='Settings']/text[@caption='Settings']", 30000, null, "961c7648-8a65-43f5-94e9-2cfb74c1a0ba");
                _clearallbuttonInfo = new RepoItemInfo(this, "ClearAllButton", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnClearAll']/?/?/text[@automationid='txtClearAll']", 30000, null, "34a27949-466d-45f0-abe3-a69fce7a1112");
                _downbuttonInfo = new RepoItemInfo(this, "DownButton", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/button[@automationid='BtnDown']", 30000, null, "f4b8ede6-528e-4157-b3e4-27dfc6902180");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3abe4702-7a2a-49b5-9ce5-6bffc3b79c09")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3abe4702-7a2a-49b5-9ce5-6bffc3b79c09")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Events item.
            /// </summary>
            [RepositoryItem("4183af41-4796-44a1-bd7e-2a12007c9685")]
            public virtual Ranorex.Text Events
            {
                get
                {
                    return _eventsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Events item info.
            /// </summary>
            [RepositoryItemInfo("4183af41-4796-44a1-bd7e-2a12007c9685")]
            public virtual RepoItemInfo EventsInfo
            {
                get
                {
                    return _eventsInfo;
                }
            }

            /// <summary>
            /// The Assessment item.
            /// </summary>
            [RepositoryItem("f467e039-f019-4623-a22f-fc7c774a4428")]
            public virtual Ranorex.Text Assessment
            {
                get
                {
                    return _assessmentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Assessment item info.
            /// </summary>
            [RepositoryItemInfo("f467e039-f019-4623-a22f-fc7c774a4428")]
            public virtual RepoItemInfo AssessmentInfo
            {
                get
                {
                    return _assessmentInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Bleeding item.
            /// </summary>
            [RepositoryItem("d96134e7-3d36-4879-a68b-fa7b2edf4f8a")]
            public virtual Ranorex.CheckBox GroupEnd_Bleeding
            {
                get
                {
                    return _groupend_bleedingInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Bleeding item info.
            /// </summary>
            [RepositoryItemInfo("d96134e7-3d36-4879-a68b-fa7b2edf4f8a")]
            public virtual RepoItemInfo GroupEnd_BleedingInfo
            {
                get
                {
                    return _groupend_bleedingInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("8cf123a8-22ae-4d60-aef2-87fe8cadd2b5")]
            public virtual Ranorex.Button General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("8cf123a8-22ae-4d60-aef2-87fe8cadd2b5")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The AddEvent item.
            /// </summary>
            [RepositoryItem("939785a1-caff-4f77-84f7-8c1a91a5daa7")]
            public virtual Ranorex.Text AddEvent
            {
                get
                {
                    return _addeventInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddEvent item info.
            /// </summary>
            [RepositoryItemInfo("939785a1-caff-4f77-84f7-8c1a91a5daa7")]
            public virtual RepoItemInfo AddEventInfo
            {
                get
                {
                    return _addeventInfo;
                }
            }

            /// <summary>
            /// The YesButtonForMultipleFunctions item.
            /// </summary>
            [RepositoryItem("ef085c54-f750-4259-9f5d-406068e77ac7")]
            public virtual Ranorex.Button YesButtonForMultipleFunctions
            {
                get
                {
                    return _yesbuttonformultiplefunctionsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButtonForMultipleFunctions item info.
            /// </summary>
            [RepositoryItemInfo("ef085c54-f750-4259-9f5d-406068e77ac7")]
            public virtual RepoItemInfo YesButtonForMultipleFunctionsInfo
            {
                get
                {
                    return _yesbuttonformultiplefunctionsInfo;
                }
            }

            /// <summary>
            /// The AddLabel item.
            /// </summary>
            [RepositoryItem("d7a16218-0d86-4e14-9a03-eef36d86bf7f")]
            public virtual Ranorex.Text AddLabel
            {
                get
                {
                    return _addlabelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddLabel item info.
            /// </summary>
            [RepositoryItemInfo("d7a16218-0d86-4e14-9a03-eef36d86bf7f")]
            public virtual RepoItemInfo AddLabelInfo
            {
                get
                {
                    return _addlabelInfo;
                }
            }

            /// <summary>
            /// The AddBlank item.
            /// </summary>
            [RepositoryItem("9af0fb06-20ae-4605-94bb-21c649c61aae")]
            public virtual Ranorex.Text AddBlank
            {
                get
                {
                    return _addblankInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddBlank item info.
            /// </summary>
            [RepositoryItemInfo("9af0fb06-20ae-4605-94bb-21c649c61aae")]
            public virtual RepoItemInfo AddBlankInfo
            {
                get
                {
                    return _addblankInfo;
                }
            }

            /// <summary>
            /// The DeleteButton item.
            /// </summary>
            [RepositoryItem("2ca62249-66d3-4bfa-b4fb-bc405ece68b5")]
            public virtual Ranorex.Text DeleteButton
            {
                get
                {
                    return _deletebuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DeleteButton item info.
            /// </summary>
            [RepositoryItemInfo("2ca62249-66d3-4bfa-b4fb-bc405ece68b5")]
            public virtual RepoItemInfo DeleteButtonInfo
            {
                get
                {
                    return _deletebuttonInfo;
                }
            }

            /// <summary>
            /// The EditButton item.
            /// </summary>
            [RepositoryItem("df487ab5-509c-4e26-8661-415914efae77")]
            public virtual Ranorex.Text EditButton
            {
                get
                {
                    return _editbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditButton item info.
            /// </summary>
            [RepositoryItemInfo("df487ab5-509c-4e26-8661-415914efae77")]
            public virtual RepoItemInfo EditButtonInfo
            {
                get
                {
                    return _editbuttonInfo;
                }
            }

            /// <summary>
            /// The File item.
            /// </summary>
            [RepositoryItem("727965fd-e55a-485c-865f-45460c41236a")]
            public virtual Ranorex.Text File
            {
                get
                {
                    return _fileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File item info.
            /// </summary>
            [RepositoryItemInfo("727965fd-e55a-485c-865f-45460c41236a")]
            public virtual RepoItemInfo FileInfo
            {
                get
                {
                    return _fileInfo;
                }
            }

            /// <summary>
            /// The ReportTypeDropDown item.
            /// </summary>
            [RepositoryItem("2fe382a2-9685-4939-9d9f-f9bded694e2e")]
            public virtual Ranorex.Button ReportTypeDropDown
            {
                get
                {
                    return _reporttypedropdownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReportTypeDropDown item info.
            /// </summary>
            [RepositoryItemInfo("2fe382a2-9685-4939-9d9f-f9bded694e2e")]
            public virtual RepoItemInfo ReportTypeDropDownInfo
            {
                get
                {
                    return _reporttypedropdownInfo;
                }
            }

            /// <summary>
            /// The Settings item.
            /// </summary>
            [RepositoryItem("961c7648-8a65-43f5-94e9-2cfb74c1a0ba")]
            public virtual Ranorex.Text Settings
            {
                get
                {
                    return _settingsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Settings item info.
            /// </summary>
            [RepositoryItemInfo("961c7648-8a65-43f5-94e9-2cfb74c1a0ba")]
            public virtual RepoItemInfo SettingsInfo
            {
                get
                {
                    return _settingsInfo;
                }
            }

            /// <summary>
            /// The ClearAllButton item.
            /// </summary>
            [RepositoryItem("34a27949-466d-45f0-abe3-a69fce7a1112")]
            public virtual Ranorex.Text ClearAllButton
            {
                get
                {
                    return _clearallbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ClearAllButton item info.
            /// </summary>
            [RepositoryItemInfo("34a27949-466d-45f0-abe3-a69fce7a1112")]
            public virtual RepoItemInfo ClearAllButtonInfo
            {
                get
                {
                    return _clearallbuttonInfo;
                }
            }

            /// <summary>
            /// The DownButton item.
            /// </summary>
            [RepositoryItem("f4b8ede6-528e-4157-b3e4-27dfc6902180")]
            public virtual Ranorex.Button DownButton
            {
                get
                {
                    return _downbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DownButton item info.
            /// </summary>
            [RepositoryItemInfo("f4b8ede6-528e-4157-b3e4-27dfc6902180")]
            public virtual RepoItemInfo DownButtonInfo
            {
                get
                {
                    return _downbuttonInfo;
                }
            }

            /// <summary>
            /// The MainDG folder.
            /// </summary>
            [RepositoryFolder("cc1a136b-ec31-4e34-96af-bb6a1256d4cf")]
            public virtual EventsFolders.MainDGFolder MainDG
            {
                get { return _maindg; }
            }
        }

        /// <summary>
        /// The MainDGFolder folder.
        /// </summary>
        [RepositoryFolder("cc1a136b-ec31-4e34-96af-bb6a1256d4cf")]
        public partial class MainDGFolder : RepoGenBaseFolder
        {
            RepoItemInfo _groupend_cardiacarrestInfo;
            RepoItemInfo _groupend_chockingInfo;
            RepoItemInfo _groupend_confusedInfo;
            RepoItemInfo _groupend_disorientedInfo;
            RepoItemInfo _groupend_faintedInfo;
            RepoItemInfo _groupend_lossofpulseInfo;
            RepoItemInfo _groupend_seizureInfo;
            RepoItemInfo _groupend_respiratoryarrestInfo;
            RepoItemInfo _groupend_roscInfo;
            RepoItemInfo _groupend_vomitedInfo;
            RepoItemInfo _general_bleedingInfo;
            RepoItemInfo _generaltabbleedingInfo;
            RepoItemInfo _generaltabscrolldownInfo;
            RepoItemInfo _newaddedeventInfo;
            RepoItemInfo _codereservedlabelInfo;
            RepoItemInfo _codereservedblankInfo;
            RepoItemInfo _airwayintactInfo;

            /// <summary>
            /// Creates a new MainDG  folder.
            /// </summary>
            public MainDGFolder(RepoGenBaseFolder parentFolder) :
                    base("MainDG", "?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']/?/?/table[@automationid='mainDG']", parentFolder, 30000, null, false, "cc1a136b-ec31-4e34-96af-bb6a1256d4cf", "")
            {
                _groupend_cardiacarrestInfo = new RepoItemInfo(this, "GroupEnd_CardiacArrest", "?/?/row[@index='1']/list/?/?/checkbox", 30000, null, "739d84f9-18d6-444a-a0dc-b8eae45dfff1");
                _groupend_chockingInfo = new RepoItemInfo(this, "GroupEnd_Chocking", "?/?/row[@index='2']/list/?/?/checkbox", 30000, null, "51a7ceda-24c4-46d9-a467-a8d026d5796a");
                _groupend_confusedInfo = new RepoItemInfo(this, "GroupEnd_Confused", "?/?/row[@index='3']/list/?/?/checkbox", 30000, null, "375bd45a-3423-4d1c-b685-9ec39c66e36a");
                _groupend_disorientedInfo = new RepoItemInfo(this, "GroupEnd_Disoriented", "?/?/row[@index='4']/list/?/?/checkbox", 30000, null, "0f22253f-a5d4-46d0-bab8-1e8b0f6e5d69");
                _groupend_faintedInfo = new RepoItemInfo(this, "GroupEnd_Fainted", "?/?/row[@index='5']/list/?/?/checkbox", 30000, null, "3d77241e-99fe-4f4e-b854-f6e69a1838fb");
                _groupend_lossofpulseInfo = new RepoItemInfo(this, "GroupEnd_LossOfPulse", "?/?/row[@index='6']/list/?/?/checkbox", 30000, null, "9d5c45a0-54fe-484d-9d85-ebc3e22cbcf9");
                _groupend_seizureInfo = new RepoItemInfo(this, "GroupEnd_Seizure", "?/?/row[@index='7']/list/?/?/checkbox", 30000, null, "35580cce-39d9-4b6d-979d-fc9df3c1b2aa");
                _groupend_respiratoryarrestInfo = new RepoItemInfo(this, "GroupEnd_RespiratoryArrest", "?/?/row[@index='8']/list/?/?/checkbox", 30000, null, "84580109-bb34-4109-a9b8-3efe584f526a");
                _groupend_roscInfo = new RepoItemInfo(this, "GroupEnd_ROSC", "?/?/row[@index='9']/list/?/?/checkbox", 30000, null, "fe71842e-83c1-4ffb-9d54-9cece28f6716");
                _groupend_vomitedInfo = new RepoItemInfo(this, "GroupEnd_Vomited", "?/?/row[@index='10']/list/?/?/checkbox", 30000, null, "20df56c9-e4a2-44ed-9104-6be475487cdf");
                _general_bleedingInfo = new RepoItemInfo(this, "General_Bleeding", "?/?/row[@index='0']/list/cell[@columnindex='3']/checkbox", 30000, null, "f5f96745-592d-470f-ae4d-5904d130913d");
                _generaltabbleedingInfo = new RepoItemInfo(this, "GeneralTabBleeding", "?/?/row[@index='24']/?/?/cell[@text='Bleeding']", 30000, null, "baf8bc04-de44-471b-9157-f46b62179cd4");
                _generaltabscrolldownInfo = new RepoItemInfo(this, "GeneralTabScrollDown", "?/?/scrollbar[@automationid='PART_VerticalScrollBar']/slider/button[2]", 30000, null, "f2dcc235-80f3-4ce2-878c-a912d40f2207");
                _newaddedeventInfo = new RepoItemInfo(this, "NewAddedEvent", "?/?/row[@index='11']/list/cell[@text='NewEvent']", 30000, null, "d8e0c683-d6d5-492d-9e8d-8428f4906f65");
                _codereservedlabelInfo = new RepoItemInfo(this, "CODERESERVEDLABEL", "?/?/row[@index='12']/?/?/cell[@text='CODE_RESERVED_LABEL']", 30000, null, "55186d83-a095-411e-aa20-3ad00e44aefd");
                _codereservedblankInfo = new RepoItemInfo(this, "CODERESERVEDBLANK", "?/?/row[@index='11']/?/?/cell[@text='CODE_RESERVED_BLANK']", 30000, null, "afcf2b0b-d877-4327-8176-88a64ad3561c");
                _airwayintactInfo = new RepoItemInfo(this, "AirwayIntact", ".//cell[@text='Airway Intact']", 30000, null, "977b7b12-a7a4-4cf7-a721-ba4532f917cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cc1a136b-ec31-4e34-96af-bb6a1256d4cf")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cc1a136b-ec31-4e34-96af-bb6a1256d4cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_CardiacArrest item.
            /// </summary>
            [RepositoryItem("739d84f9-18d6-444a-a0dc-b8eae45dfff1")]
            public virtual Ranorex.CheckBox GroupEnd_CardiacArrest
            {
                get
                {
                    return _groupend_cardiacarrestInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_CardiacArrest item info.
            /// </summary>
            [RepositoryItemInfo("739d84f9-18d6-444a-a0dc-b8eae45dfff1")]
            public virtual RepoItemInfo GroupEnd_CardiacArrestInfo
            {
                get
                {
                    return _groupend_cardiacarrestInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Chocking item.
            /// </summary>
            [RepositoryItem("51a7ceda-24c4-46d9-a467-a8d026d5796a")]
            public virtual Ranorex.CheckBox GroupEnd_Chocking
            {
                get
                {
                    return _groupend_chockingInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Chocking item info.
            /// </summary>
            [RepositoryItemInfo("51a7ceda-24c4-46d9-a467-a8d026d5796a")]
            public virtual RepoItemInfo GroupEnd_ChockingInfo
            {
                get
                {
                    return _groupend_chockingInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Confused item.
            /// </summary>
            [RepositoryItem("375bd45a-3423-4d1c-b685-9ec39c66e36a")]
            public virtual Ranorex.CheckBox GroupEnd_Confused
            {
                get
                {
                    return _groupend_confusedInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Confused item info.
            /// </summary>
            [RepositoryItemInfo("375bd45a-3423-4d1c-b685-9ec39c66e36a")]
            public virtual RepoItemInfo GroupEnd_ConfusedInfo
            {
                get
                {
                    return _groupend_confusedInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Disoriented item.
            /// </summary>
            [RepositoryItem("0f22253f-a5d4-46d0-bab8-1e8b0f6e5d69")]
            public virtual Ranorex.CheckBox GroupEnd_Disoriented
            {
                get
                {
                    return _groupend_disorientedInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Disoriented item info.
            /// </summary>
            [RepositoryItemInfo("0f22253f-a5d4-46d0-bab8-1e8b0f6e5d69")]
            public virtual RepoItemInfo GroupEnd_DisorientedInfo
            {
                get
                {
                    return _groupend_disorientedInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Fainted item.
            /// </summary>
            [RepositoryItem("3d77241e-99fe-4f4e-b854-f6e69a1838fb")]
            public virtual Ranorex.CheckBox GroupEnd_Fainted
            {
                get
                {
                    return _groupend_faintedInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Fainted item info.
            /// </summary>
            [RepositoryItemInfo("3d77241e-99fe-4f4e-b854-f6e69a1838fb")]
            public virtual RepoItemInfo GroupEnd_FaintedInfo
            {
                get
                {
                    return _groupend_faintedInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_LossOfPulse item.
            /// </summary>
            [RepositoryItem("9d5c45a0-54fe-484d-9d85-ebc3e22cbcf9")]
            public virtual Ranorex.CheckBox GroupEnd_LossOfPulse
            {
                get
                {
                    return _groupend_lossofpulseInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_LossOfPulse item info.
            /// </summary>
            [RepositoryItemInfo("9d5c45a0-54fe-484d-9d85-ebc3e22cbcf9")]
            public virtual RepoItemInfo GroupEnd_LossOfPulseInfo
            {
                get
                {
                    return _groupend_lossofpulseInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Seizure item.
            /// </summary>
            [RepositoryItem("35580cce-39d9-4b6d-979d-fc9df3c1b2aa")]
            public virtual Ranorex.CheckBox GroupEnd_Seizure
            {
                get
                {
                    return _groupend_seizureInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Seizure item info.
            /// </summary>
            [RepositoryItemInfo("35580cce-39d9-4b6d-979d-fc9df3c1b2aa")]
            public virtual RepoItemInfo GroupEnd_SeizureInfo
            {
                get
                {
                    return _groupend_seizureInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_RespiratoryArrest item.
            /// </summary>
            [RepositoryItem("84580109-bb34-4109-a9b8-3efe584f526a")]
            public virtual Ranorex.CheckBox GroupEnd_RespiratoryArrest
            {
                get
                {
                    return _groupend_respiratoryarrestInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_RespiratoryArrest item info.
            /// </summary>
            [RepositoryItemInfo("84580109-bb34-4109-a9b8-3efe584f526a")]
            public virtual RepoItemInfo GroupEnd_RespiratoryArrestInfo
            {
                get
                {
                    return _groupend_respiratoryarrestInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_ROSC item.
            /// </summary>
            [RepositoryItem("fe71842e-83c1-4ffb-9d54-9cece28f6716")]
            public virtual Ranorex.CheckBox GroupEnd_ROSC
            {
                get
                {
                    return _groupend_roscInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_ROSC item info.
            /// </summary>
            [RepositoryItemInfo("fe71842e-83c1-4ffb-9d54-9cece28f6716")]
            public virtual RepoItemInfo GroupEnd_ROSCInfo
            {
                get
                {
                    return _groupend_roscInfo;
                }
            }

            /// <summary>
            /// The GroupEnd_Vomited item.
            /// </summary>
            [RepositoryItem("20df56c9-e4a2-44ed-9104-6be475487cdf")]
            public virtual Ranorex.CheckBox GroupEnd_Vomited
            {
                get
                {
                    return _groupend_vomitedInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The GroupEnd_Vomited item info.
            /// </summary>
            [RepositoryItemInfo("20df56c9-e4a2-44ed-9104-6be475487cdf")]
            public virtual RepoItemInfo GroupEnd_VomitedInfo
            {
                get
                {
                    return _groupend_vomitedInfo;
                }
            }

            /// <summary>
            /// The General_Bleeding item.
            /// </summary>
            [RepositoryItem("f5f96745-592d-470f-ae4d-5904d130913d")]
            public virtual Ranorex.CheckBox General_Bleeding
            {
                get
                {
                    return _general_bleedingInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The General_Bleeding item info.
            /// </summary>
            [RepositoryItemInfo("f5f96745-592d-470f-ae4d-5904d130913d")]
            public virtual RepoItemInfo General_BleedingInfo
            {
                get
                {
                    return _general_bleedingInfo;
                }
            }

            /// <summary>
            /// The GeneralTabBleeding item.
            /// </summary>
            [RepositoryItem("baf8bc04-de44-471b-9157-f46b62179cd4")]
            public virtual Ranorex.Cell GeneralTabBleeding
            {
                get
                {
                    return _generaltabbleedingInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The GeneralTabBleeding item info.
            /// </summary>
            [RepositoryItemInfo("baf8bc04-de44-471b-9157-f46b62179cd4")]
            public virtual RepoItemInfo GeneralTabBleedingInfo
            {
                get
                {
                    return _generaltabbleedingInfo;
                }
            }

            /// <summary>
            /// The GeneralTabScrollDown item.
            /// </summary>
            [RepositoryItem("f2dcc235-80f3-4ce2-878c-a912d40f2207")]
            public virtual Ranorex.Button GeneralTabScrollDown
            {
                get
                {
                    return _generaltabscrolldownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GeneralTabScrollDown item info.
            /// </summary>
            [RepositoryItemInfo("f2dcc235-80f3-4ce2-878c-a912d40f2207")]
            public virtual RepoItemInfo GeneralTabScrollDownInfo
            {
                get
                {
                    return _generaltabscrolldownInfo;
                }
            }

            /// <summary>
            /// The NewAddedEvent item.
            /// </summary>
            [RepositoryItem("d8e0c683-d6d5-492d-9e8d-8428f4906f65")]
            public virtual Ranorex.Cell NewAddedEvent
            {
                get
                {
                    return _newaddedeventInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The NewAddedEvent item info.
            /// </summary>
            [RepositoryItemInfo("d8e0c683-d6d5-492d-9e8d-8428f4906f65")]
            public virtual RepoItemInfo NewAddedEventInfo
            {
                get
                {
                    return _newaddedeventInfo;
                }
            }

            /// <summary>
            /// The CODERESERVEDLABEL item.
            /// </summary>
            [RepositoryItem("55186d83-a095-411e-aa20-3ad00e44aefd")]
            public virtual Ranorex.Cell CODERESERVEDLABEL
            {
                get
                {
                    return _codereservedlabelInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CODERESERVEDLABEL item info.
            /// </summary>
            [RepositoryItemInfo("55186d83-a095-411e-aa20-3ad00e44aefd")]
            public virtual RepoItemInfo CODERESERVEDLABELInfo
            {
                get
                {
                    return _codereservedlabelInfo;
                }
            }

            /// <summary>
            /// The CODERESERVEDBLANK item.
            /// </summary>
            [RepositoryItem("afcf2b0b-d877-4327-8176-88a64ad3561c")]
            public virtual Ranorex.Cell CODERESERVEDBLANK
            {
                get
                {
                    return _codereservedblankInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CODERESERVEDBLANK item info.
            /// </summary>
            [RepositoryItemInfo("afcf2b0b-d877-4327-8176-88a64ad3561c")]
            public virtual RepoItemInfo CODERESERVEDBLANKInfo
            {
                get
                {
                    return _codereservedblankInfo;
                }
            }

            /// <summary>
            /// The AirwayIntact item.
            /// </summary>
            [RepositoryItem("977b7b12-a7a4-4cf7-a721-ba4532f917cc")]
            public virtual Ranorex.Cell AirwayIntact
            {
                get
                {
                    return _airwayintactInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The AirwayIntact item info.
            /// </summary>
            [RepositoryItemInfo("977b7b12-a7a4-4cf7-a721-ba4532f917cc")]
            public virtual RepoItemInfo AirwayIntactInfo
            {
                get
                {
                    return _airwayintactInfo;
                }
            }
        }

        /// <summary>
        /// The EventEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("d366b60e-7983-4b93-86d7-dfa7102a6af6")]
        public partial class EventEditorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new EventEditor  folder.
            /// </summary>
            public EventEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EventEditor", "/form[@title='Event Editor']", parentFolder, 30000, null, true, "d366b60e-7983-4b93-86d7-dfa7102a6af6", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "5bad8956-2039-4969-bafa-46c91f568816");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d366b60e-7983-4b93-86d7-dfa7102a6af6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d366b60e-7983-4b93-86d7-dfa7102a6af6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("5bad8956-2039-4969-bafa-46c91f568816")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("5bad8956-2039-4969-bafa-46c91f568816")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The AddEventAppFolder folder.
        /// </summary>
        [RepositoryFolder("a486d313-ff3b-4730-9492-0d89acb5363b")]
        public partial class AddEventAppFolder : RepoGenBaseFolder
        {
            EventsFolders.DgNameFolder _dgname;

            /// <summary>
            /// Creates a new AddEvent  folder.
            /// </summary>
            public AddEventAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddEvent", "/form[@title='Add Event']", parentFolder, 30000, null, true, "a486d313-ff3b-4730-9492-0d89acb5363b", "")
            {
                _dgname = new EventsFolders.DgNameFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a486d313-ff3b-4730-9492-0d89acb5363b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a486d313-ff3b-4730-9492-0d89acb5363b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DgName folder.
            /// </summary>
            [RepositoryFolder("72a04c24-8e37-4d4a-80f1-61f655c05bd8")]
            public virtual EventsFolders.DgNameFolder DgName
            {
                get { return _dgname; }
            }
        }

        /// <summary>
        /// The DgNameFolder folder.
        /// </summary>
        [RepositoryFolder("72a04c24-8e37-4d4a-80f1-61f655c05bd8")]
        public partial class DgNameFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _codeInfo;
            RepoItemInfo _eventnameInfo;

            /// <summary>
            /// Creates a new DgName  folder.
            /// </summary>
            public DgNameFolder(RepoGenBaseFolder parentFolder) :
                    base("DgName", "table[@automationid='dgName']", parentFolder, 30000, null, false, "72a04c24-8e37-4d4a-80f1-61f655c05bd8", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "?/?/button[@automationid='btnOK']", 30000, null, "f45b9002-b556-441b-9ac8-ff34e7076c6e");
                _codeInfo = new RepoItemInfo(this, "Code", "?/?/text[@automationid='txtID']", 30000, null, "22c7c2c7-b0f9-4af3-a285-1ad3fd8f2c7e");
                _eventnameInfo = new RepoItemInfo(this, "EventName", "row/list/?/?/text[@caption='']", 30000, null, "b1715879-7de8-40ab-9264-4ab8138e8e51");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("72a04c24-8e37-4d4a-80f1-61f655c05bd8")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("72a04c24-8e37-4d4a-80f1-61f655c05bd8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("f45b9002-b556-441b-9ac8-ff34e7076c6e")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("f45b9002-b556-441b-9ac8-ff34e7076c6e")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The Code item.
            /// </summary>
            [RepositoryItem("22c7c2c7-b0f9-4af3-a285-1ad3fd8f2c7e")]
            public virtual Ranorex.Text Code
            {
                get
                {
                    return _codeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Code item info.
            /// </summary>
            [RepositoryItemInfo("22c7c2c7-b0f9-4af3-a285-1ad3fd8f2c7e")]
            public virtual RepoItemInfo CodeInfo
            {
                get
                {
                    return _codeInfo;
                }
            }

            /// <summary>
            /// The EventName item.
            /// </summary>
            [RepositoryItem("b1715879-7de8-40ab-9264-4ab8138e8e51")]
            public virtual Ranorex.Text EventName
            {
                get
                {
                    return _eventnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EventName item info.
            /// </summary>
            [RepositoryItemInfo("b1715879-7de8-40ab-9264-4ab8138e8e51")]
            public virtual RepoItemInfo EventNameInfo
            {
                get
                {
                    return _eventnameInfo;
                }
            }
        }

        /// <summary>
        /// The EditEventAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ac9a3bc-1bf2-428f-b9df-d7570de27621")]
        public partial class EditEventAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editingeventnameInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new EditEvent  folder.
            /// </summary>
            public EditEventAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EditEvent", "/form[@title='Edit Event']", parentFolder, 30000, null, true, "7ac9a3bc-1bf2-428f-b9df-d7570de27621", "")
            {
                _editingeventnameInfo = new RepoItemInfo(this, "EditingEventName", "table[@automationid='dgName']/row/list/?/?/text[@caption='NewEvent']", 30000, null, "6f497806-521e-423a-b028-f7a4c694a0aa");
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "table[@automationid='dgName']/?/?/button[@automationid='btnOK']", 30000, null, "cf8423f5-aa96-4340-a430-edc47e13d663");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ac9a3bc-1bf2-428f-b9df-d7570de27621")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ac9a3bc-1bf2-428f-b9df-d7570de27621")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EditingEventName item.
            /// </summary>
            [RepositoryItem("6f497806-521e-423a-b028-f7a4c694a0aa")]
            public virtual Ranorex.Text EditingEventName
            {
                get
                {
                    return _editingeventnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EditingEventName item info.
            /// </summary>
            [RepositoryItemInfo("6f497806-521e-423a-b028-f7a4c694a0aa")]
            public virtual RepoItemInfo EditingEventNameInfo
            {
                get
                {
                    return _editingeventnameInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("cf8423f5-aa96-4340-a430-edc47e13d663")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("cf8423f5-aa96-4340-a430-edc47e13d663")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
