///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TempusSimulatorDemoTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LaunchAppPage element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("cfa05188-5c96-4b10-a237-80a306844845")]
    public partial class LaunchAppPage : RepoGenBaseFolder
    {
        static LaunchAppPage instance = new LaunchAppPage();
        LaunchAppPageFolders.LaunchAppPageElementsAppFolder _launchapppageelements;

        /// <summary>
        /// Gets the singleton class instance representing the LaunchAppPage element repository.
        /// </summary>
        [RepositoryFolder("cfa05188-5c96-4b10-a237-80a306844845")]
        public static LaunchAppPage Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LaunchAppPage() 
            : base("LaunchAppPage", "/", null, 0, false, "cfa05188-5c96-4b10-a237-80a306844845", ".\\RepositoryImages\\LaunchAppPagecfa05188.rximgres")
        {
            _launchapppageelements = new LaunchAppPageFolders.LaunchAppPageElementsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cfa05188-5c96-4b10-a237-80a306844845")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LaunchAppPageElements folder.
        /// </summary>
        [RepositoryFolder("f615fbd7-f37d-4501-b164-65165565f976")]
        public virtual LaunchAppPageFolders.LaunchAppPageElementsAppFolder LaunchAppPageElements
        {
            get { return _launchapppageelements; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LaunchAppPageFolders
    {
        /// <summary>
        /// The LaunchAppPageElementsAppFolder folder.
        /// </summary>
        [RepositoryFolder("f615fbd7-f37d-4501-b164-65165565f976")]
        public partial class LaunchAppPageElementsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _eventsInfo;
            RepoItemInfo _new_patient_defaultsInfo;
            RepoItemInfo _communicationsInfo;
            RepoItemInfo _codes_otherInfo;
            RepoItemInfo _newitemInfo;

            /// <summary>
            /// Creates a new LaunchAppPageElements  folder.
            /// </summary>
            public LaunchAppPageElementsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LaunchAppPageElements", "", parentFolder, 30000, null, false, "f615fbd7-f37d-4501-b164-65165565f976", "")
            {
                _eventsInfo = new RepoItemInfo(this, "Events", "/form[@title>'Tempus Pro Configuration']/?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='Events']", 30000, null, "c8fe3bcd-e0d3-4e88-8314-cab0cafd3d06");
                _new_patient_defaultsInfo = new RepoItemInfo(this, "New_Patient_Defaults", "/form[@title>'Tempus Pro Configuration']/?/?/tabpagelist[@automationid='mainTab']/tabpage[@title='New patient defaults']", 30000, null, "243c7417-4470-4a04-8247-ae62f6b2ffa3");
                _communicationsInfo = new RepoItemInfo(this, "Communications", "/form[@title>'Tempus Pro Configuration']/?/?/tabpagelist[@automationid='mainTab']/?/?/text[@caption='Communications']", 30000, null, "1a047064-1388-4362-ba9e-3802c06c6faf");
                _codes_otherInfo = new RepoItemInfo(this, "Codes_Other", "/form[@title>'Tempus Pro Configuration']/?/?/tabpagelist[@automationid='mainTab']/?/?/text[@caption='Codes / Other']", 30000, null, "f64e047a-c154-4b2b-a79b-96ef41016a57");
                _newitemInfo = new RepoItemInfo(this, "NewItem", "/element", 30000, null, "9987fbfe-e99f-4f51-bf34-94bb187038a3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f615fbd7-f37d-4501-b164-65165565f976")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f615fbd7-f37d-4501-b164-65165565f976")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Events item.
            /// </summary>
            [RepositoryItem("c8fe3bcd-e0d3-4e88-8314-cab0cafd3d06")]
            public virtual Ranorex.TabPage Events
            {
                get
                {
                    return _eventsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Events item info.
            /// </summary>
            [RepositoryItemInfo("c8fe3bcd-e0d3-4e88-8314-cab0cafd3d06")]
            public virtual RepoItemInfo EventsInfo
            {
                get
                {
                    return _eventsInfo;
                }
            }

            /// <summary>
            /// The New_Patient_Defaults item.
            /// </summary>
            [RepositoryItem("243c7417-4470-4a04-8247-ae62f6b2ffa3")]
            public virtual Ranorex.TabPage New_Patient_Defaults
            {
                get
                {
                    return _new_patient_defaultsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The New_Patient_Defaults item info.
            /// </summary>
            [RepositoryItemInfo("243c7417-4470-4a04-8247-ae62f6b2ffa3")]
            public virtual RepoItemInfo New_Patient_DefaultsInfo
            {
                get
                {
                    return _new_patient_defaultsInfo;
                }
            }

            /// <summary>
            /// The Communications item.
            /// </summary>
            [RepositoryItem("1a047064-1388-4362-ba9e-3802c06c6faf")]
            public virtual Ranorex.Text Communications
            {
                get
                {
                    return _communicationsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Communications item info.
            /// </summary>
            [RepositoryItemInfo("1a047064-1388-4362-ba9e-3802c06c6faf")]
            public virtual RepoItemInfo CommunicationsInfo
            {
                get
                {
                    return _communicationsInfo;
                }
            }

            /// <summary>
            /// The Codes_Other item.
            /// </summary>
            [RepositoryItem("f64e047a-c154-4b2b-a79b-96ef41016a57")]
            public virtual Ranorex.Text Codes_Other
            {
                get
                {
                    return _codes_otherInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Codes_Other item info.
            /// </summary>
            [RepositoryItemInfo("f64e047a-c154-4b2b-a79b-96ef41016a57")]
            public virtual RepoItemInfo Codes_OtherInfo
            {
                get
                {
                    return _codes_otherInfo;
                }
            }

            /// <summary>
            /// The NewItem item.
            /// </summary>
            [RepositoryItem("9987fbfe-e99f-4f51-bf34-94bb187038a3")]
            public virtual Ranorex.Unknown NewItem
            {
                get
                {
                    return _newitemInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NewItem item info.
            /// </summary>
            [RepositoryItemInfo("9987fbfe-e99f-4f51-bf34-94bb187038a3")]
            public virtual RepoItemInfo NewItemInfo
            {
                get
                {
                    return _newitemInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
