///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TempusSimulatorDemoTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the LoadConfiguration element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("07f75ec0-e66e-4dfc-b068-b4acc31568d4")]
    public partial class LoadConfiguration : RepoGenBaseFolder
    {
        static LoadConfiguration instance = new LoadConfiguration();
        LoadConfigurationFolders.LoadConfigWebElementsFolder _loadconfigwebelements;

        /// <summary>
        /// Gets the singleton class instance representing the LoadConfiguration element repository.
        /// </summary>
        [RepositoryFolder("07f75ec0-e66e-4dfc-b068-b4acc31568d4")]
        public static LoadConfiguration Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public LoadConfiguration() 
            : base("LoadConfiguration", "/", null, 0, false, "07f75ec0-e66e-4dfc-b068-b4acc31568d4", ".\\RepositoryImages\\LoadConfiguration07f75ec0.rximgres")
        {
            _loadconfigwebelements = new LoadConfigurationFolders.LoadConfigWebElementsFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("07f75ec0-e66e-4dfc-b068-b4acc31568d4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The LoadConfigWebElements folder.
        /// </summary>
        [RepositoryFolder("3980275e-80ac-4579-b187-2ce8b4485189")]
        public virtual LoadConfigurationFolders.LoadConfigWebElementsFolder LoadConfigWebElements
        {
            get { return _loadconfigwebelements; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class LoadConfigurationFolders
    {
        /// <summary>
        /// The LoadConfigWebElementsFolder folder.
        /// </summary>
        [RepositoryFolder("3980275e-80ac-4579-b187-2ce8b4485189")]
        public partial class LoadConfigWebElementsFolder : RepoGenBaseFolder
        {
            LoadConfigurationFolders.TempusProConfigurationUtility1AppFolder _tempusproconfigurationutility1;
            LoadConfigurationFolders.BrowseForFolderAppFolder _browseforfolder;
            LoadConfigurationFolders.TempusProConfigurationUtilityAppFolder _tempusproconfigurationutility;

            /// <summary>
            /// Creates a new LoadConfigWebElements  folder.
            /// </summary>
            public LoadConfigWebElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("LoadConfigWebElements", "", parentFolder, 0, null, false, "3980275e-80ac-4579-b187-2ce8b4485189", "")
            {
                _tempusproconfigurationutility1 = new LoadConfigurationFolders.TempusProConfigurationUtility1AppFolder(this);
                _browseforfolder = new LoadConfigurationFolders.BrowseForFolderAppFolder(this);
                _tempusproconfigurationutility = new LoadConfigurationFolders.TempusProConfigurationUtilityAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3980275e-80ac-4579-b187-2ce8b4485189")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TempusProConfigurationUtility1 folder.
            /// </summary>
            [RepositoryFolder("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual LoadConfigurationFolders.TempusProConfigurationUtility1AppFolder TempusProConfigurationUtility1
            {
                get { return _tempusproconfigurationutility1; }
            }

            /// <summary>
            /// The BrowseForFolder folder.
            /// </summary>
            [RepositoryFolder("c0157edc-8592-4e7f-89a7-d688857337f6")]
            public virtual LoadConfigurationFolders.BrowseForFolderAppFolder BrowseForFolder
            {
                get { return _browseforfolder; }
            }

            /// <summary>
            /// The TempusProConfigurationUtility folder.
            /// </summary>
            [RepositoryFolder("45912f2a-d09d-46bb-a2c7-2544b7e4658d")]
            public virtual LoadConfigurationFolders.TempusProConfigurationUtilityAppFolder TempusProConfigurationUtility
            {
                get { return _tempusproconfigurationutility; }
            }
        }

        /// <summary>
        /// The TempusProConfigurationUtility1AppFolder folder.
        /// </summary>
        [RepositoryFolder("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
        public partial class TempusProConfigurationUtility1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loadInfo;

            /// <summary>
            /// Creates a new TempusProConfigurationUtility1  folder.
            /// </summary>
            public TempusProConfigurationUtility1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("TempusProConfigurationUtility1", "/contextmenu[@processname='Tempus Pro Configuration Utility']", parentFolder, 30000, null, false, "62c266cf-85b9-42ab-a1ab-a3eb362160fc", "")
            {
                _loadInfo = new RepoItemInfo(this, "Load", "menuitem[@text='Load']", 30000, null, "b1b1a096-0dc4-4584-b9f7-056b22f9c74e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("62c266cf-85b9-42ab-a1ab-a3eb362160fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Load item.
            /// </summary>
            [RepositoryItem("b1b1a096-0dc4-4584-b9f7-056b22f9c74e")]
            public virtual Ranorex.MenuItem Load
            {
                get
                {
                    return _loadInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Load item info.
            /// </summary>
            [RepositoryItemInfo("b1b1a096-0dc4-4584-b9f7-056b22f9c74e")]
            public virtual RepoItemInfo LoadInfo
            {
                get
                {
                    return _loadInfo;
                }
            }
        }

        /// <summary>
        /// The BrowseForFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0157edc-8592-4e7f-89a7-d688857337f6")]
        public partial class BrowseForFolderAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _treeitem601033tempusproconfigInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new BrowseForFolder  folder.
            /// </summary>
            public BrowseForFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BrowseForFolder", "/form[@title='Browse For Folder']", parentFolder, 30000, null, true, "c0157edc-8592-4e7f-89a7-d688857337f6", "")
            {
                _treeitem601033tempusproconfigInfo = new RepoItemInfo(this, "TreeItem601033TempusProConfig", "element[@class='SHBrowseForFolder ShellNameSpace Control']/tree[@controlid='100']//treeitem[@text='Amlan']/?/?/treeitem[@text='601033-TempusProConfig']", 30000, null, "d9bd2bdd-b5f2-45bd-aec5-60a3e92d9c62");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "41567570-ba2f-4b74-aa40-9a5c08ed2aea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0157edc-8592-4e7f-89a7-d688857337f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0157edc-8592-4e7f-89a7-d688857337f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TreeItem601033TempusProConfig item.
            /// </summary>
            [RepositoryItem("d9bd2bdd-b5f2-45bd-aec5-60a3e92d9c62")]
            public virtual Ranorex.TreeItem TreeItem601033TempusProConfig
            {
                get
                {
                    return _treeitem601033tempusproconfigInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TreeItem601033TempusProConfig item info.
            /// </summary>
            [RepositoryItemInfo("d9bd2bdd-b5f2-45bd-aec5-60a3e92d9c62")]
            public virtual RepoItemInfo TreeItem601033TempusProConfigInfo
            {
                get
                {
                    return _treeitem601033tempusproconfigInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("41567570-ba2f-4b74-aa40-9a5c08ed2aea")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("41567570-ba2f-4b74-aa40-9a5c08ed2aea")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The TempusProConfigurationUtilityAppFolder folder.
        /// </summary>
        [RepositoryFolder("45912f2a-d09d-46bb-a2c7-2544b7e4658d")]
        public partial class TempusProConfigurationUtilityAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _file1Info;

            /// <summary>
            /// Creates a new TempusProConfigurationUtility  folder.
            /// </summary>
            public TempusProConfigurationUtilityAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TempusProConfigurationUtility", "/form[@title>'Tempus Pro Configuration']", parentFolder, 30000, null, true, "45912f2a-d09d-46bb-a2c7-2544b7e4658d", "")
            {
                _file1Info = new RepoItemInfo(this, "File1", "?/?/menuitem[@text='File']/text[@caption='File']", 30000, null, "feeb4191-8e10-4bde-930d-54d4d35cdd4e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45912f2a-d09d-46bb-a2c7-2544b7e4658d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45912f2a-d09d-46bb-a2c7-2544b7e4658d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The File1 item.
            /// </summary>
            [RepositoryItem("feeb4191-8e10-4bde-930d-54d4d35cdd4e")]
            public virtual Ranorex.Text File1
            {
                get
                {
                    return _file1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The File1 item info.
            /// </summary>
            [RepositoryItemInfo("feeb4191-8e10-4bde-930d-54d4d35cdd4e")]
            public virtual RepoItemInfo File1Info
            {
                get
                {
                    return _file1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
