///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TempusSimulatorDemoTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("4965f498-19d8-4b41-83e9-626df5690f1c", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TempusSimulatorDemoTest1Repository repository.
        /// </summary>
        public static TempusSimulatorDemoTest1Repository repo = TempusSimulatorDemoTest1Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TempusProConfigurationUtility.ToggleButton' at 90;11.", repo.TempusProConfigurationUtility.ToggleButtonInfo, new RecordItemIndex(0));
            repo.TempusProConfigurationUtility.ToggleButton.Click("90;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'TempusProConfigurationUtility.ToggleButton' at 76;8.", repo.TempusProConfigurationUtility.ToggleButtonInfo, new RecordItemIndex(1));
            repo.TempusProConfigurationUtility.ToggleButton.MoveTo("76;8");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'TempusProConfigurationUtility.ToggleButton' at 158;8.", repo.TempusProConfigurationUtility.ToggleButtonInfo, new RecordItemIndex(2));
            repo.TempusProConfigurationUtility.ToggleButton.MoveTo("158;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TempusProConfigurationUtility1.ListItemTC3' at 44;4.", repo.TempusProConfigurationUtility1.ListItemTC3Info, new RecordItemIndex(3));
            repo.TempusProConfigurationUtility1.ListItemTC3.Click("44;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TempusProConfigurationUtility.Settings' at 13;9.", repo.TempusProConfigurationUtility.SettingsInfo, new RecordItemIndex(4));
            repo.TempusProConfigurationUtility.Settings.Click("13;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TempusProConfigurationUtility1.HighlightTC3LinkedEvents' at 30;4.", repo.TempusProConfigurationUtility1.HighlightTC3LinkedEventsInfo, new RecordItemIndex(5));
            repo.TempusProConfigurationUtility1.HighlightTC3LinkedEvents.Click("30;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
